### ISSUE TITLE
Picture data usage

### ISSUE THREAD

**Issue by HipyCas** [TianyiShi2001/audiotags#16]
I am trying yo use this library to parse the data from some files, and everything works perfectly fine expect the cover data. I cannot get to understant what data it is passing to me, as it is neither divisible by 3 nor 4. ¿Any idea on how to get the pixels from the array?

(My current objective is to render it in JS using a canvas, which needs an array of RGBA values)

**Comment by Serial-ATA** [comment]
Tags embed the full image file, if you need it decoded you should check out the [image crate](https://crates.io/crates/image).

**Comment by pinkforest** [comment]
Closing as answered
