### ISSUE TITLE
[Question] Cover Art from .m4a/.mp3 Files

### ISSUE THREAD

**Issue by bradleat** [TianyiShi2001/audiotags#24]
I am unable to read cover art from `m4a` and `mp3` files. These are just songs that I have purchased from there Apple Music Store (iTunes)

 For example:

```rust
let tag = Tag::new().read_from_path(p.clone()).unwrap();

let album_cover_mime: String = tag.album_cover().map(|cover| cover.mime_type).unwrap_or(MimeType::Tiff).into();
let picture_data = tag.album_cover().map(|cover| cover.data).unwrap_or_default().to_vec();
```

The `album_cover_mime` is set to default, and the `picture_data` vec is empty.

Am I doing something wrong?

**Comment by Serial-ATA** [comment]
Do the files have front covers? You can make a test program to check your `mp3` files with the [`id3`](https://crates.io/crates/id3) crate and check the pictures with [`Tag::pictures`](https://docs.rs/id3/1.5.0/id3/struct.Tag.html#method.pictures). It could be an issue with the `id3` crate.

**Comment by pinkforest** [comment]
There is no way to replicate this issue - Please re-open if there is data to reproduce this in order to fix it. Thanks
