### ISSUE TITLE
Support for comment tag

### ISSUE THREAD

**Issue by a1049145827** [TianyiShi2001/audiotags#31]

**Comment by pinkforest** [comment]
This is very specific to Id3 I think ? Is there equivalent for other formats

I think this is in [id3::frame::Comment](https://docs.rs/id3/latest/id3/frame/struct.Comment.html) and there is also [id3::frame::Lyrics](https://docs.rs/id3/latest/id3/frame/struct.Lyrics.html) similar to Picture we already have.

@Serial-ATA I know this is probably out of scope to abstract at audiotags level ?

Would it be worthwhile exposing this low level information opportunistically ?

**Comment by Serial-ATA** [comment]
> This is very specific to Id3 I think ? Is there equivalent for other formats

Comments exist in all 3 of the tag formats supported. The thing is, ID3v2 provides way more options for comments, opposed to MP4 ilst and Vorbis Comments which are just simple strings.

It'd probably be more trouble than it's worth to add these complex items to a crate this high-level. If you need to support more items outside of the basic title, album, artist, etc. then I'd recommend just using [lofty](https://crates.io/crates/lofty).

**Comment by pinkforest** [comment]
Ok cool - sounds like #44 applies here and better to direct to lofty
