### ISSUE TITLE
Bitrate support

### ISSUE THREAD

**Issue by fililip** [TianyiShi2001/audiotags#32]
There's currently no way of reading bitrate information for audio files.
Was that simply missed or is there a reason it's not implemented for `audiotags` (i.e. the underlying metadata crates don't expose that kind of information)?

**Comment by Serial-ATA** [comment]
The information would be provided for MP4 and FLAC files, but it would not be available in ID3 tags.

That's different from the duration, which can be both determined by the file's contents with `mp4ameta` and `metaflac`, *and* taken from the ID3 tag with `id3`.

This crate focuses on the *tag* of the file, not any other contents that could be used to gather additional information on the properties. Attempting to add it into here would lead to an empty implementation for ID3, which is not desirable.

**Comment by fililip** [comment]
Alright, thanks for the clarification.
Is there any other crate that exposes audio bitrate info that you're aware of?

**Comment by Serial-ATA** [comment]
Yep, I maintain one :smile:. https://github.com/Serial-ATA/lofty-rs

**Comment by fililip** [comment]
Thanks a lot!
