### ISSUE TITLE
Request for release

### ISSUE THREAD

**Issue by Ralim** [TianyiShi2001/audiotags#38]
Hello,
Its been a while since #21 has been merged in; along with four more PR's merged in this year adding features.

Would be great to have a new release tagged out with these changes if possible?

Are there any blocker issues preventing a new release I can look at helping with?

Sorry to create more noise 😅

**Comment by Serial-ATA** [comment]
Hey @pinkforest any interest in doing this? There are a couple PRs (#34, #37) to get merged as well. I've reviewed both and they are ready.

**Comment by pinkforest** [comment]
Thanks @Ralim and Thanks @Serial-ATA - I was going to add the publish to the org so you can release as well but seemingly forgot.

I'm behind on things but will get to it after next week's weekend - I am stuffed atm

**Comment by pinkforest** [comment]
@Serial-ATA could you do the honors ? :pray: e.g. send a PR with changelog + version bump

**Comment by Serial-ATA** [comment]
Sure, I'll get it done shortly.

**Comment by emesterhazy** [comment]
Hi everyone, happy new year! Any chance we can get this pushed through in the next couple of weeks? 🙏

**Comment by pinkforest** [comment]
There was a release so closing this
