### ISSUE TITLE
Would it be possible to add composer support

### ISSUE THREAD

**Issue by ChousX** [TianyiShi2001/audiotags#4]
There is one piece of metadata I still want that is composer.

**Comment by pinkforest** [comment]
We just made heaps of changes and I was wonderin if that metadata is still not there then if you have an example file I can try to fish it out

**Comment by Serial-ATA** [comment]
It's not there, I can add it soon though :slightly_smiling_face:.

**Comment by pinkforest** [comment]
That would be lovely thanks @Serial-ATA  :)

**Comment by pinkforest** [comment]
@ChousX would you mind testing now from with the version off git main ?
