### ISSUE TITLE
Support for custom tags?

### ISSUE THREAD

**Issue by abique** [TianyiShi2001/audiotags#41]
Hi,

Would it be possible to add support for custom tags?
By custom tag, I mean a key and value pair.

Cheers,
Alex

**Comment by abique** [comment]
Actually, I didn't realize there was a `get_first()` for flac.
Is it applicable to all file types?

**Comment by Serial-ATA** [comment]
It is only applicable for `FlacTag`, since the keys are just simple strings. Handling ID3v2 frame IDs and MP4 ilst atom identifiers would likely be out of scope, as they both come in different forms.

For more complex metadata handling, I'd suggest using another crate.

**Comment by pinkforest** [comment]
What would be the reason for custom tags ? e.g. use-cases why this would be a good idea

**Comment by abique** [comment]
> What would be the reason for custom tags ? e.g. use-cases why this would be a good idea

To store cue points, loops, beat info, custom attributes ...

**Comment by Serial-ATA** [comment]
If you need more complex metadata handling, you should use [lofty](https://crates.io/crates/lofty). `audiotags` is more intended to provide high-level view of a few basic items in the tag.
