### ISSUE TITLE
Fail to write Tag

### ISSUE THREAD

**Issue by DagBjorndal** [TianyiShi2001/audiotags#48]
I've written a Rust program to clean meta data in my music library. 

For some .m4a files in ALAC format, the write_to_path() function fails with Mp4TagError(Io(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }): Error reading atom length).

For these files; just reading and directly writing back the tag fails:

    let mut tag = Tag::new().read_from_path(path.as_path()).unwrap();
    tag.write_to_path(path.to_str().unwrap()).unwrap();

As far as I can see, these tags seem fine in other software e.g. Kid3.

**Comment by pinkforest** [comment]
This needs to be [re-producible](https://en.wikipedia.org/wiki/Minimal_reproducible_example).

Re-open if it can be re-produced so it can be potentially both tested and fixed if any real bugs found through that.

**Comment by DagBjorndal** [comment]
This is 100% reproducible for the same media files. The exact same error message is also given using crates **mp4meta** or **mtag**.
