### ISSUE TITLE
how to read audio files from memory

### ISSUE THREAD

**Issue by LuckyTurtleDev** [TianyiShi2001/audiotags#51]
hi i am working at wasm and would like to use this create to parse audio meta data. since the program runs at a browser i can not use the file system. instead i get `Vec<u8>` which stores the file.

**Comment by Serial-ATA** [comment]
I imagine all of the backend crates allow you to read/write with `Vec<u8>`, so it should be straightforward to add support if you want to make a PR.

Otherwise, you could use [lofty](https://docs.rs/lofty) which is WASM compatible.

**Comment by LuckyTurtleDev** [comment]
@Serial-ATA  Thanks for the create recommendation. I have  start using symphonia and mp4ameta (symphonia was not able to parse metadata from m4b/mp4).
But lofty looks promising too. I will probably replace mp4ameta with it.

Although the issue is solved for me, i keep open the issue, since this feature is something which is still useful for this create.
@TianyiShi2001 feel free to close.

:christmas_tree: :santa:

**Comment by pinkforest** [comment]
lofty provides this, closing.
