### ISSUE TITLE
`read_from_path` should not panic without extension

### ISSUE THREAD

**Issue by woelper** [TianyiShi2001/audiotags#7]
currently, extensions are handled like this:
```rust
path.as_ref()
    .extension()
    .unwrap()
    .to_string_lossy()
    .to_string()
    .to_lowercase()
    .as_str(),
```
Which could panic due to the `unwrap()`.
as `try_from_ext` already handles extensions, maybe we could `unwrap_or` into an empty `OsStr` or use `?`?

**Comment by pinkforest** [comment]
Hm. We just re-merged audiotags2 into audiotags and there were a lot of changes.

I think these unwraps may be still there - I have to check

Please feel free to send a PR to fix and put some erroring if you find panic'y unwraps
